myApp/urls.py
from django.conf.urls import url
from . import views
import myApp

app_name = 'myApp'

urlpatterns = [
    url(r'^$', views.index),  # 主页

    # 登录页
    url(r'^StudentLogin/$', views.student_login, name = 'StudentLogin'),  # 学生登陆
    url(r'^TeacherLogin/$', views.teacher_login, name = 'TeacherLogin'),  # 教师登陆
    url(r'^ReselectPassword/$', views.reselect_password, name = 'ReselectPassword'),  # 修改密码界面

    # 个人主页
    url(r'^TeacherIndex/$', views.teacher_index, name = 'TeacherIndex'),  # 教师主页
    url(r'^StudentIndex/$', views.student_index, name = 'StudentIndex'),  # 学生主页

    # 添加新学生账号
    url(r'^SelectAddStudentInfo', views.select_add_student_info, name = 'SelectAddStudentInfo'),  # 选择添加学生班级信息
    url(r'^SingleAddStudent', views.single_add_student, name = 'SingleAddStudent'),  # 单独添加学生信息
    # TODO :: 应当先清除session

    # 人脸识别准备
    url(r'^StudentUploadPhoto/$', views.student_upload_photo, name = 'StudentUploadPhoto'),  # 学生上传照片页
    url(r'^LaunchSignIn/$', views.launch_sign_in, name = 'LaunchSignIn'),  # 教师发起签到页
    url(r'^face/$', views.snap, name = 'face'),  # 人脸识别拍照主页
    url(r'^recognition/$', views.recognition, name = 'recognition'),  # 人脸识别结果显示页
    url(r'^ClearSession/$', views.clear_session, name = 'ClearSession'),  # 清除人脸识别造成的session并返回教师主页

    # 辅助
    url(r'^verifycode/$', views.verifycode, name = 'verifycode'),  # 验证码
    url(r'^OutLogin/$', views.out_login, name = 'OutLogin'),  # 注销
    url(r'^favicon.ico/$', views.return_favicon_ico, name = 'favicon'), # 获得favicon.ico
    url(r'^Todo/$', views.todo, name = 'todo'),

    # LaunchSignIn Select标签的三级联动
    url(r'^AjaxGetMajor/$', views.ajax_get_major, name = 'AjaxGetMajor'),  # Ajax根据学院获得专业
    url(r'^AjaxGetGrade/$', views.ajax_get_grade, name = 'AjaxGetGrade'),  # Ajax根据专业获得班级
]

# 404/500
# handler404 = myApp.views.page_not_found
# handler500 = myApp.views.page_error
# !404/500

project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

# 解决了将Debug设置为False后Static文件无法加载问题
from django.views import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('myApp.urls'), name='myApp'),
    url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}, name='static'), # 404/500
]

myApp/models.py
from django.db import models


# Create your models here.

# DIY Model Objects Manager
class ModelManager(models.Manager):
    def get_queryset(self):
        return super(ModelManager, self).get_queryset().filter(isDelete = False)


# 权限信息数据表
class IdentityInformation(models.Model):
    role_name = models.CharField(max_length = 20, primary_key = True)

    def __str__(self):
        return "%s" % self.role_name

    class Meta:
        db_table = "identity"


# 学院信息数据表
class CollegeInformation(models.Model):
    college_name = models.CharField(max_length = 40, unique = True)

    def __str__(self):
        return "%s" % self.college_name

    class Meta:
        db_table = "college"


# 专业信息数据表
class MajorInformation(models.Model):
    major_name = models.CharField(max_length = 40, unique = True)

    def __str__(self):
        return "%s" % self.major_name

    class Meta:
        db_table = "major"


# 班级信息数据表
class GradeInformation(models.Model):
    grade_name = models.CharField(max_length = 40, unique = True)

    def __str__(self):
        return "%s" % self.grade_name

    class Meta:
        db_table = "grade"


# 详细班级信息数据表
class DetailGradeInformation(models.Model):
    college_id = models.ForeignKey(CollegeInformation, to_field = 'college_name', on_delete = models.CASCADE)
    major_id = models.ForeignKey(MajorInformation, to_field = 'major_name', on_delete = models.CASCADE)
    grade_id = models.ForeignKey(GradeInformation, to_field = 'grade_name', on_delete = models.CASCADE)
    student_num = models.IntegerField(default = 0)

    def __str__(self):
        return "%s-%s-%s" % (self.college_id.college_name, self.major_id.major_name, self.grade_id.grade_name)

    class Meta:
        db_table = "user_grade"


# 签到信息数据表
class SignInformation(models.Model):
    sign_time = models.DateTimeField(auto_now_add = True)
    initiator = models.IntegerField()
    target = models.ForeignKey(DetailGradeInformation, on_delete = models.CASCADE)
    reached = models.IntegerField()
    actual = models.IntegerField()

    def __str__(self):
        return "%s" % str(self.sign_time)

    class Meta:
        db_table = "sign"

    @classmethod
    def make_new_sign(cls, initiator, target, reached):
        sign = cls(initiator = initiator, target = target, reached = reached, actual = 0)
        return sign


# 用户信息数据表
class UserInformation(models.Model):
    account = models.CharField(max_length = 20, unique = True)
    password = models.CharField(max_length = 20)
    name = models.CharField(max_length = 20)
    gender = models.BooleanField()
    grade = models.ForeignKey(DetailGradeInformation, on_delete = models.CASCADE, null = True, blank = True)
    identity = models.ForeignKey(IdentityInformation, on_delete = models.CASCADE)
    first_create_time = models.DateTimeField(auto_now_add = True)
    last_modify_time = models.DateTimeField(auto_now = True)
    new_sign = models.BooleanField(default = True)
    isDelete = models.BooleanField(default = False)

    objects = ModelManager()  # DIY Model Objects Manager

    def __str__(self):
        return "%s" % self.name

    class Meta:
        db_table = "user"

    @classmethod
    def add_student(cls, account, password, name, gender):
        new_student = cls(account = account, password = password, name = name, gender = gender)
        return new_student

myApp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import logout
from . import models
from aip import AipFace
from pypinyin import lazy_pinyin

import json


# Create your views here.

# 获得中文名对应的英文名
# 格式：王钦弘  -->  WangQinhong
def get_en_name(zh_name):
    en_list = lazy_pinyin(zh_name)
    xing = en_list[0]
    ming = ""
    for y in en_list[1:]:
        ming += y
    en = xing.title().lstrip() + ming.title().lstrip()
    en.title().lstrip()
    return en


# 检查登陆信息
def check_login(request, account, password, verify_code, identity):
    # 先比对验证码，CSRF
    if verify_code != request.session['verify_code'].upper():
        return False
    # 从数据库中拿account和password去比对
    try:
        models.UserInformation.objects.get(account = account, password = password, identity = identity)
    except (models.UserInformation.DoesNotExist, models.UserInformation.MultipleObjectsReturned):
        return False
    return True


# 检查为了人脸识别签到所选择的学院-专业-班级信息是否正确
# 并且检查班级人数是否合法
# CMG: College Major Grade
def check_select_cmg_info(request, college, major, grade):
    try:
        grade_info = list(models.DetailGradeInformation.objects.values().filter(college_id__college_name = college,
                                                                                major_id__major_name = major,
                                                                                grade_id__grade_name = grade))
    except models.DetailGradeInformation.DoesNotExist:
        print("Error in views.py 48 : DetailGradeInformation.DoesNotExist")
        return False
    if grade_info[0]['student_num'] < 1:
        # 班级人数非法
        print("Error in view.py 52 : Does not have any Student in this grade")
        return False
    else:
        # 设置session，为了签到页面使用
        request.session['sign_college'] = college
        request.session['sign_major'] = major
        request.session['sign_grade'] = grade
        request.session['sign_student_num'] = grade_info[0]['student_num']
        # 超长代码段来了！
        sign_students_info = {}
        temp_list = []
        students_list = list(models.UserInformation.objects.all().filter(
            grade = models.DetailGradeInformation.objects.get(
                college_id__college_name = college,
                major_id__major_name = major,
                grade_id__grade_name = grade),
            identity = 'Student').values())
        for student in students_list:
            temp_list.append(student['name'])
            temp_list.append(False)
            sign_students_info[get_en_name(student['name'])] = temp_list
            temp_list = []
        # 至此已经获得了对应签到班级的所有学生姓名
        # 存储在了一个字典中，英文名:[中文名，是否签到(default=False)]
        request.session['sign_student_info'] = sign_students_info
    return True


# 为了发起签到而做准备
def ready_to_face_sign(request, college, major, grade):
    # 设置签到日志
    teacher_name = request.session['user_name']
    teacher_id = models.UserInformation.objects.get(name = teacher_name, identity = 'Teacher')
    grade_info = models.DetailGradeInformation.objects.get(college_id__college_name = college,
                                                           major_id__major_name = major,
                                                           grade_id__grade_name = grade)
    new_sign = models.SignInformation.make_new_sign(initiator = teacher_id.id,
                                                    reached = request.session['sign_student_num'],
                                                    target = grade_info)
    new_sign.save()
    request.session['sign_id'] = new_sign.id
    print("Set new sign Successful!")


# 主页
def index(request):
    if request.method == 'POST':
        return render(request, 'myApp/todo.html', None)
    logout(request)
    return render(request, 'myApp/index.html', None)


# 学生登陆页
def student_login(request):
    login_fail = False
    if request.method == "POST":
        account = request.POST.get("form-username")
        password = request.POST.get("form-password")
        verify_code = request.POST.get("form-verifycode").upper()
        if check_login(request, account, password, verify_code, identity = 'Student'):
            this_student = models.UserInformation.objects.get(account = account)
            user_name = this_student.name
            new_sign = this_student.new_sign
            request.session['user_name'] = user_name
            request.session['user_account'] = account
            request.session.set_expiry(0)
            # 检查是否第一次登陆并令其修改密码
            if new_sign is True:
                return HttpResponseRedirect("/ReselectPassword/?identity=Student")
            return HttpResponseRedirect("/StudentIndex/")
        else:
            login_fail = True
    elif request.method == "GET":
        login_fail = False

    return render(request, 'myApp/StudentsLogin.html', {'login_fail': login_fail})


# 教师登录页
def teacher_login(request):
    login_fail = False
    if request.method == "POST":
        account = request.POST.get("form-username")
        password = request.POST.get("form-password")
        verify_code = request.POST.get("form-verifycode").upper()
        if check_login(request, account, password, verify_code, identity = 'Teacher'):
            this_teacher = models.UserInformation.objects.get(account = account)
            user_name = this_teacher.name
            new_sign = this_teacher.new_sign
            request.session['user_name'] = user_name
            request.session['user_account'] = account
            request.session.set_expiry(0)
            # 检查是否第一次登陆并令其修改密码
            if new_sign is True:
                return HttpResponseRedirect("/ReselectPassword/?identity=Teacher")
            return HttpResponseRedirect("/TeacherIndex/")
        else:
            login_fail = True
    elif request.method == "GET":
        login_fail = False
    return render(request, 'myApp/TeachersLogin.html', {'login_fail': login_fail})


# 学生个人主页
def student_index(request):
    if request.method == 'POST':
        return render(request, 'myApp/todo.html', None)
    user_name = request.session.get('user_name', default = None)
    return render(request, 'myApp/StudentIndex.html', {"user_name": user_name})


# 教师个人主页
def teacher_index(request):
    if request.method == 'POST':
        return render(request, 'myApp/todo.html', None)
    user_name = request.session.get('user_name', default = None)
    return render(request, 'myApp/TeacherIndex.html', {"user_name": user_name})


# 下面的三个函数：
# LaunchSignIn、AjaxGetMajor、AjaxGetGrade
# 于2019/02/17 凌晨 3:37 实现
# 在经历了无数次老泪纵横于心态爆炸
# 终于实现了，谨此纪念
# 救命稻草：
# Django web开发中的二级联动select 列表的简单实现方法
# https://blog.csdn.net/qq_42469759/article/details/82834264
#                                               --- 王钦弘

def launch_sign_in(request):
    select_fail = False
    user_name = request.session.get('user_name', default = None)
    college_list = []
    if request.method == 'POST':
        # 确认信息后发起签到
        college = request.POST.get('college_name', default = None)
        major = request.POST.get('major_name', default = None)
        grade = request.POST.get('grade_name', default = None)
        if check_select_cmg_info(request, college, major, grade):
            # 为发起签到做准备
            ready_to_face_sign(request, college, major, grade)
            return HttpResponseRedirect('/face/')
        else:
            print("check false")
            select_fail = True
    elif request.method == 'GET':
        select_fail = False
        try:
            college_list = models.DetailGradeInformation.objects.all().values('college_id__college_name').distinct()
        except models.DetailGradeInformation.DoesNotExist:
            return render(request, 'myApp/LaunchSignIn.html', {"user_name": user_name})
    return render(request, 'myApp/LaunchSignIn.html',
                  {"user_name": user_name,
                   "college_list": college_list,
                   "select_fail": select_fail})


def ajax_get_major(request):
    major_result = 0
    if request.method == 'GET':
        college_select = request.GET.get('select_college', None)
        # print('get college from ajax "%s"' % (college_select))
        if college_select:
            data = list(models.DetailGradeInformation.objects.filter(
                college_id__college_name = college_select).values('major_id__major_name').distinct())
            major_result = json.dumps(data)
            # print(major_result)
    return HttpResponse(major_result, "application/json")


def ajax_get_grade(request):
    grade_result = 0
    if request.method == 'GET':
        major_select = request.GET.get('select_major', None)
        # print('get major from ajax "%s"' % (major_select))
        if major_select:
            data = list(models.DetailGradeInformation.objects.filter(
                major_id__major_name = major_select).values('grade_id__grade_name').distinct())
            grade_result = json.dumps(data)
            # print(grade_result)
    return HttpResponse(grade_result, "application/json")


# 人脸识别签到页
def face(photo_image, group_id_list):
    app_id = '14807296'
    api_key = 'HrRWN5CIoqfr2Xje4SwUdKdK'
    secret_key = 'fGupsKW4qtIrqYW3bA5ToiLk19oO483X'
    client = AipFace(appId = app_id, apiKey = api_key, secretKey = secret_key)

    image_type = "BASE64"
    # groupIdList = "001"
    options = dict()
    options['liveness_control'] = 'LOW'
    options['quality_control'] = 'NORMAL'
    # photoImage = base64.b64encode(photoImage)
    result = client.search(photo_image, image_type, group_id_list, options)
    return result


# 获得学生当前人脸库中有多少照片
def get_student_photo_numbers(requset, group_id_list):
    app_id = '14807296'
    api_key = 'HrRWN5CIoqfr2Xje4SwUdKdK'
    secret_key = 'fGupsKW4qtIrqYW3bA5ToiLk19oO483X'
    client = AipFace(appId = app_id, apiKey = api_key, secretKey = secret_key)

    user_id = get_en_name(str(requset.session.get('user_name')))

templates/myApp/ReselectPassword.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>修改密码</title>
    <!-- CSS -->
    <link rel="stylesheet" href="{% static "myApp/ReselectPassword/bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "myApp/ReselectPassword/font-awesome/css/font-awesome.min.css" %}">
    <link rel="stylesheet" href="{% static "myApp/ReselectPassword/css/form-elements.css" %}">
    <link rel="stylesheet" href="{% static "myApp/ReselectPassword/css/style.css" %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

    <!-- Favicon and touch icons -->
    <link rel="shortcut icon" href="{% static "myApp/ReselectPassword/ico/favicon.png" %}">
    <link rel="apple-touch-icon-precomposed" sizes="144x144"
          href="{% static "myApp/ReselectPassword/ico/apple-touch-icon-144-precomposed.png" %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114"
          href="{% static "myApp/ReselectPassword/ico/apple-touch-icon-114-precomposed.png" %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72"
          href="{% static "myApp/ReselectPassword/ico/apple-touch-icon-72-precomposed.png" %}">
    <link rel="apple-touch-icon-precomposed"
          href="{% static "myApp/ReselectPassword/ico/apple-touch-icon-57-precomposed.png" %}">

</head>

<body>

<!-- Top content -->
<div class="top-content">
    <div class="inner-bg">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-sm-offset-2 text">
                    <h1><strong>Modify</strong> Password</h1>
                    <div class="description">
                        <p>
                            在这里修改您的密码：
                        </p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 col-sm-offset-3 form-box">
                    <div class="form-top">
                        <div class="form-top-left">
                            <h3>{{ user_name }} {{ user_identity }}</h3>
                            <p>{{ why_select }}，为了账号安全请修改密码。</p>
                        </div>
                        <div class="form-top-right">
                            <i class="fa fa-lock"></i>
                        </div>
                    </div>
                    <div class="form-bottom">
                        <form role="form" method="post" class="login-form">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="sr-only" for="form-password">旧密码</label>
                                <input type="password" name="form-password-old" placeholder="旧密码..."
                                       class="form-password form-control" id="form-password-pld">
                            </div>
                            <div class="form-group">
                                <label class="sr-only" for="form-password">新密码</label>
                                <input type="password" name="form-password-new" placeholder="新密码..."
                                       class="form-password form-control" id="form-password-new">
                            </div>
                            <div class="form-group">
                                <label class="sr-only" for="form-password">确认新密码</label>
                                <input type="password" name="form-password-again" placeholder="请再次输入新密码..."
                                       class="form-password form-control" id="form-password-again">
                            </div>
                            <div class="form-group">
                                <label class="sr-only">验证码</label>
                                <input type="text" name="form-verifycode" placeholder="验证码..."/>
                                <a href="{% url 'myApp:ReselectPassword' %}"><img src="{% url 'myApp:verifycode' %}"
                                                                                  alt="验证码" title="看不清？点击刷新"></a>
                            </div>
                            <button type="submit" class="btn"><i class="fa fa-sign-in"></i> 修改并登陆!</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

{% if user_name is None %}
    <script language="JavaScript">
        alert("您还未登陆！请先登录！");
        window.location.href = '/';
    </script>
{% endif %}

<!-- Javascript -->
<script src="{% static "myApp/ReselectPassword/js/jquery-1.11.1.min.js" %}"></script>
<script src="{% static "myApp/ReselectPassword/bootstrap/js/bootstrap.min.js" %}"></script>
<script src="{% static "myApp/ReselectPassword/js/jquery.backstretch.min.js" %}"></script>
<script>$.backstretch("{% static "myApp/ReselectPassword/img/backgrounds/1.jpg" %}");</script>
<script src="{% static "myApp/ReselectPassword/js/scripts.js" %}"></script>

<!--[if lt IE 10]>
            <script src="{% static "myApp/ReselectPassword/js/placeholder.js" %}></script>
        <![endif]-->

</body>

</html>

templates/myApp/SelectAddStudentInfo.html
{% load static %}
{% csrf_token %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% if select_fail is True %}
        <script language="JavaScript">
            alert("选择失败！请重新选择！");
            window.location.href = '{% url "myApp:SelectAddStudentInfo" %}';
        </script>
    {% endif %}

    {% if user_name is None %}
        <script language="JavaScript">
            alert("您还未登陆！请先登录！");
            window.location.href = '/';
        </script>
    {% endif %}

    <meta charset="UTF-8">
    <title>AddStudent</title>
    <link href="{% static 'myApp/SelectAddStudentInfo/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'myApp/SelectAddStudentInfo/bower_components/flexslider/flexslider.css' %}" rel="stylesheet">
    <link href="{% static 'myApp/SelectAddStudentInfo/css/scrolling-nav.css' %}" rel="stylesheet">
    <link href="{% static 'myApp/SelectAddStudentInfo/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'myApp/SelectAddStudentInfo/css/responsive.css' %}" rel="stylesheet">
    <link href="{% static 'myApp/SelectAddStudentInfo/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'myApp/SelectAddStudentInfo/css/headline.css' %}" rel="stylesheet">
    <link href="{% static 'myApp/SelectAddStudentInfo/ionicons/css/ionicons.min.css' %}" rel="stylesheet">
    <!-- Important Owl stylesheet -->
    <link rel="stylesheet"
          href="{% static 'myApp/SelectAddStudentInfo/bower_components/owl-carousel/owl.carousel.css' %}">

    <!-- Default Theme -->
    <link rel="stylesheet" href="{% static 'myApp/SelectAddStudentInfo/bower_components/owl-carousel/owl.theme.css' %}">
    <style>
        * {
            padding: 0;
            margin: 0;
        }

        .main_content {
            width: 70%;
            margin: auto;
            padding-top: 133px;
            height: 800px;
        }

        .main_control {
            height: 45px;
        }

        .selectList {
            height: 175px;
        }
    </style>
</head>
<body>
<!--导航栏-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-header" style="display: inline-block; padding-top: 30px"></div>
    <div class="container-fluid"></div>
    <div class="container">
        <div class="navbar-header page-scroll">
            <p class="nav navbar-nav navbar-left">
                <h1>添加新的学生信息！
                    <small style="color: darkgray">&nbsp;选择我们，为您提供更好的用户体验</small>
                </h1>
            </p>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav navbar-right">
                <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                <li>
                    {% if user_name is None %}
                        <a class="page-scroll">欢迎！游客</a>
                    {% else %}
                        <a class="page-scroll">欢迎您！{{ user_name }}老师</a>
                    {% endif %}
                </li>
                <li>
                    {% if user_name is None %}
                        <a class="page-scroll" href="/">点此登陆</a>
                    {% else %}
                        <a href="{% url 'myApp:OutLogin' %}" class="page-scroll">注销</a>
                    {% endif %}
                </li>
                <li>
                    <a class="page-scroll" href="{% url 'myApp:TeacherIndex' %}">返回主页</a>
                </li>
                <li>
                    <a class="page-scroll" href="{% url 'myApp:todo' %}">联系我们</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!--main_content-->
<div class="main_content">
    <div class="main_control"></div>
    <div class="row">
        <div class="col-xs-6"><img src="{% static 'myApp/SelectAddStudentInfo/images/logo.png' %}" alt=""
                                   class="img-circle"></div>
        <div class="col-xs-6"><p style="font-size: 25px">请在下方表单中选择新学生班级：</p>
            <p>&nbsp;</p>
            <p>请注意，一定要记得勾选添加学生信息个数（单个/批量）</p>
            <p>单独添加为手动填写一个新学生的姓名和账号；</p>
            <p>批量添加为从一个Excel表中按照班级批量导入；</p><br/>
            <p>了解更多：<a href='javascript:alert("暂未开放");'>Excel表格格式要求</a></p>
        </div>
    </div>
    <div id="select_info">
        <div class="main_control"></div>
        <form class="form-horizontal" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            <div class="selectList">
                <div class="form-group">
                    <label class="col-sm-2 control-label">学院</label>
                    <div class="col-sm-10">
                        <select class="form-control" name="college_name" id="college_name"
                                onchange="ajaxgetcollege(this);">
                            <option value="">---学院---</option>
                            {% for college in college_list %}
                                <option value="{{ college.college_id__college_name }}">{{ college.college_id__college_name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">专业</label>
                    <div class="col-sm-10">
                        <select class="form-control" name="major_name" id="major_name" onchange="ajaxgetmajor(this);">
                            <option value="">---专业---</option>
{#                            这里利用js直接返回了html代码，所以不用Django模板#}
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">班级</label>
                    <div class="col-sm-10">
                        <select class="form-control" name="grade_name" id="grade_name" onchange="ajaxgetgrade(this);">
                            <option value="">---班级---</option>
{#                            这里利用js直接返回了html代码，所以不用Django模板#}
                        </select>
                    </div>
                </div>
                <div class="form-group" style="padding-top: 10px">
                    <div class="col-sm-offset-2 col-sm-10">
                        <label>单独添加学生</label>
                        <input type="radio" value="single_add" name="SelectMode" checked="checked"/>
                        <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;批量导入学生</label>
                        <input type="radio" value="batch_add" name="SelectMode" disabled="disabled"/>
                    </div>
                </div>
            </div>
            <div class="form-group" style="padding-top: 20px">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">提交</button>
                </div>
            </div>
        </form>
    </div>
</div>


<div class="footer-bottom" style="height: 125px">
    <div class="container">
        <div class="col-lg-6 col-md-6 col-sm-6">
            <div class="f-b">Copyright &copy; 西安科技大学-玩不了了<a href="#" target="_blank" title="玩不了了">玩不了了</a> <br/> -
                Collect from <a href="#" title="玩不了了" target="_blank">玩不了了</a></div>
        </div>
    </div>
</div>

<!-- JavaScript -->
<script src="{% static 'myApp/SelectAddStudentInfo/js/jquery-1.11.1.min.js' %}"></script>
<script src="{% static 'myApp/SelectAddStudentInfo/js/scripts.js' %}"></script>

<!-- Scrolling Nav JavaScript -->
<script src="{% static "/myApp/SelectAddStudentInfo/js/scrolling-nav.js" %}"></script>
<script src="{% static "/myApp/SelectAddStudentInfo/js/main.js" %}"></script>
</body>
</html>